version: 2
updates:
  - package-ecosystem: "deno"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-official:
        patterns:
          - "actions/*"
